### ISSUE TITLE
Sécurité ?

### ISSUE THREAD

**Issue by fbuloup** [dmachard/python-creditagricole-particuliers#15]
Bonjour et merci pour cette api.

Je me pose néanmoins une question : les requêtes sont-elles sécurisées ?
Les numéros de comptes, mot de passe etc. sont-ils cryptés lors des différentes requêtes durant une sessions ?

Merci pour la réponse

**Comment by dmachard** [comment]
Ce client se comporte comme le portail web en utilisant les mêmes mécanismes de chiffrement et d'authentification.

**Comment by fbuloup** [comment]
merci pour cette information
