### ISSUE TITLE
Can't access aliases.json

### ISSUE THREAD

**Issue by GautMauf** [dmachard/python-creditagricole-particuliers#21]
While trying to run the Authenticator function I've got an error saying that:

FileNotFoundError: [Errno 2] No such file or directory: 'aliases.json'

Can see the file but didn't go further to fix it (maybe a directory problem in the class Authenticator

**Comment by GautMauf** [comment]
Don't have the error anymore

**Comment by dmachard** [comment]
@Elektriman can you fix this issue please ?
In the meantime @GautMauf, can you rollback to the v0.10 version ?

**Comment by Elektriman** [comment]
fix proposed at [this pull request](https://github.com/dmachard/python-creditagricole-particuliers/pull/22)

**Comment by dmachard** [comment]
New release [v0.11.1](https://github.com/dmachard/python-creditagricole-particuliers/releases/tag/v0.11.1)

**Comment by Elektriman** [comment]
The problem is not fixed. I tested it

**Comment by Elektriman** [comment]
I've posted a new solution that worked on a totally new environment so this time should be the last patch. Edit [here](https://github.com/dmachard/python-creditagricole-particuliers/pull/23)

**Comment by Elektriman** [comment]
@dmachard

**Comment by dmachard** [comment]
fix in v0.11.2
