### ISSUE TITLE
Méthode "get_operations" renvoie constamment l'erreur " KeyError: 'nextSetStartIndex' "

### ISSUE THREAD

**Issue by Obseline** [dmachard/python-creditagricole-particuliers#25]
Même avec un format de date correct : account.get_operations(date_start="2023-10-01", date_stop="2023-10-31", count=90)

L'erreur suivante ressort :
`Traceback (most recent call last):
  File "xxxxxxxx.py", line 28, in <module>
    operations = account.get_operations(date_start="2023-10-01", date_stop="2023-10-31", count=90)
  File "/usr/local/lib/python3.10/dist-packages/creditagricole_particuliers/accounts.py", line 43, in get_operations
    return operations.Operations(session=self.session,
  File "/usr/local/lib/python3.10/dist-packages/creditagricole_particuliers/operations.py", line 80, in __init__
    self.get_operations(count=count, sleep=sleep)
  File "/usr/local/lib/python3.10/dist-packages/creditagricole_particuliers/operations.py", line 141, in get_operations
    self.get_operations(nextCount, rsp["nextSetStartIndex"])
  File "/usr/local/lib/python3.10/dist-packages/creditagricole_particuliers/operations.py", line 141, in get_operations
    self.get_operations(nextCount, rsp["nextSetStartIndex"])
KeyError: 'nextSetStartIndex'
`

**Comment by dmachard** [comment]
je pense que c'est lié à la pull request #24 @Twicode  tu peux regarder stp ?
en attendant il faut rollbacker sur la version [v0.11.2](https://github.com/dmachard/python-creditagricole-particuliers/releases/tag/v0.11.2)

**Comment by Twicode** [comment]
@Obseline Cc @dmachard 
A priori la clé nextSetStartIndex n'existe pas dans la réponse de l'appel /particulier/operations/synthese/detail-comptes/jcr:content.n3.operations.json.

Est-ce que tu saurais (en cachant les opérations bien sûr) montrer le retour de l'appel ?
Ou bien, sais-tu si il y a <= 90 opérations qui sont censées être retournées ?

J'ai quand même en attendant fait un commit et une PR qui devrait régler le problème : #26

**Comment by dmachard** [comment]
@Obseline une nouvelle version a été généré, possible de tester?
@Twicode merci pour la rapidité

**Comment by Obseline** [comment]
Je confirme, en mettant à jour le package python, ça fonctionne à nouveau, merci à vous
