### ISSUE TITLE
KeyError: 'grandeFamilleProduitCode'

### ISSUE THREAD

**Issue by mattmofr** [dmachard/python-creditagricole-particuliers#32]
Lors du lancement du script proposé dans le readme, une exception KeyError est levée : 
`creditagricole_particuliers/accounts.py", line 22, in __init__`
`self.grandeFamilleCode = account["grandeFamilleProduitCode"]`
`KeyError: 'grandeFamilleProduitCode'`

**Comment by dmachard** [comment]
Pour aider, il faudrait à minima 
- la version du package utilisée
- le code associé

**Comment by mattmofr** [comment]
Je viens de tester à nouveau et c'est passé sans aucun problème...
