### ISSUE TITLE
Ne fonctionne plus en décembre 2022?

### ISSUE THREAD

**Issue by sebo83910** [dmachard/python-creditagricole-particuliers#8]
Bonjour,
J'ai suivi les instructions mais impossible de faire fonctionner cette API à ce jour.
Merci quand même!

**Comment by dmachard** [comment]
C'est quoi l'erreur ?
pas de soucis de mon côté

**Comment by sebo83910** [comment]
J'obtiens ceci avec Python 3.10.8:
Exception: [error] keypad: 500 - {"erreurType":"TECHNICAL_ERREUR_TYPE","message":"Une erreur technique est survenue. Veuillez réessayer ultérieurement."}

**Comment by sebo83910** [comment]
Peut-etre que la région n'est pas correcte: J'ai mis ceci: region="paca"

**Comment by sebo83910** [comment]
ok. C'est en regardant ton code que j'ai pu retrouver la région. En paca, le code est "pca".

**Comment by dmachard** [comment]
Je vais ajouter la liste des régions

**Comment by dmachard** [comment]
plus simple, pour la prochaine version il suffira de passer le numéro de département au niveau de l'authentification
il est possible de trouver  l'url de la banque régional associée.

**Comment by sebo83910** [comment]
Effectivement cela semble plus simple.
J'en profite pour demander comment tu utilises ce script? Pour ma part, à l'origine, je souhaiter récupérer les écritures pour pouvoir les répartir en catégories de dépenses et ainsi mieux analyser mon budget au fil du temps.
